<a href="https://colab.research.google.com/github/yash206/Data-Science-Projects/blob/main/Sales_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

In [ ]:
dataset = pd.read_csv('Book6.csv')
print(dataset)

     Age  Salary  Status
0     17   69000       0
1     47   55000       0
2     18   33000       0
3     35   97000       1
4     49   30000       1
..   ...     ...     ...
195   46   26000       1
196   46  103000       0
197   16   62000       0
198   36   97000       1
199   20   45000       0

[200 rows x 3 columns]


In [ ]:
print(dataset.shape)
print(dataset.head(5))  #we can use tail instead of head to print from back

(200, 3)
   Age  Salary  Status
0   17   69000       0
1   47   55000       0
2   18   33000       0
3   35   97000       1
4   49   30000       1


In [ ]:
X = dataset.iloc[:, :-1].values
X

array([[    17,  69000],
       [    47,  55000],
       [    18,  33000],
       [    35,  97000],
       [    49,  30000],
       [    27, 105000],
       [    39, 114000],
       [    23,  21000],
       [    39, 102000],
       [    35, 107000],
       [    28, 107000],
       [    50,  90000],
       [    43,  56000],
       [    21, 110000],
       [    33,  20000],
       [    20, 105000],
       [    27,  50000],
       [    35,  39000],
       [    47, 110000],
       [    29,  32000],
       [    48,  52000],
       [    23,  63000],
       [    26,  51000],
       [    23,  35000],
       [    15,  55000],
       [    49,  43000],
       [    35,  79000],
       [    28,  35000],
       [    25,  76000],
       [    31, 125000],
       [    35,  98000],
       [    30,  53000],
       [    27,  71000],
       [    24,  91000],
       [    37, 119000],
       [    42,  82000],
       [    39,  71000],
       [    31,  84000],
       [    29,  30000],
       [    45,  75000],


In [ ]:
Y = dataset.iloc[:, -1].values
Y

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test =  train_test_split(X,Y,test_size=0.2,random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=0)
model.fit(X_train,Y_train)

LogisticRegression(random_state=0)

In [ ]:
age = int(input("Enter New Customer's Age: "))
sal = int(input("Enter New Customer's Salary: "))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result==1:
  print("Customer will Buy")
else:
  print("Customer won't Buy")

Enter New Customer's Age: 35
Enter New Customer's Salary: 15000
[0]
Customer won't Buy


In [ ]:
Y_pred = model.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)

print("Confusion Matrix: ")
print(cm)

Confusion Matrix: 
[[18  6]
 [11  5]]


Accuracy

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy of the Model : {0}%".format(accuracy_score(Y_test,Y_pred)*100))

Accuracy of the Model : 57.49999999999999%
